### ISSUE TITLE
Switch to OFL only

### ISSUE THREAD

**Issue by davelab6** [dbenjaminmiller/domitian#2]
Would you consider using only OFL for this project?

**Comment by dbenjaminmiller** [comment]
It is under consideration: there is a certain derivative/expansion of this font which is in the works (you can email me <dbmiller@dbmiller.org> for more information), and that will likely be OFL-only.
I wanted to release my version under the same tri-license as the sources, since this offers the greatest flexibility: anybody who wants OFL can use it, but same for anybody who wants to combine the work with something which is GPL or LPPL licensed. Personally, I would like my own work to be usable for any purpose, as long as I am attributed: that I have restricted this to the tri-license is due to that being what URW made the sources available under.
But I am happy to switch to OFL-only if you have a contribution to add which requires the use of the OFL only. Please mention this if so. But if not, then I would like the user to have the maximum flexibility. Let me know if there is anything else you think I should consider.

**Comment by davelab6** [comment]
The OFL says recipients can only redistribute with the OFL, "and no other license," so this just creates a hazard for downstream users

**Comment by davelab6** [comment]
Indeed, since you are a downstream user, urw put you in this awful situation where you might be terminated. 

I speculate reason urw did that is that they had distributed the fonts under gpl, since the 80s I think, and wanted to keep doing so, using the same license as ghostscript, which is now agpl. 

The lppl when used solo is allowing downstream users to redistribute under the OFL since it meets it's terms.

So, I think you are already obligated to use only the OFL.

**Comment by dbenjaminmiller** [comment]
Interesting position. Now, before I say any of this, I must say that I am not a lawyer. And neither, as far as I know, are you. So our views are worth approximately bupkis. But we proceed anyway.
The license says the termination is automatic. So if you are correct, then I am not an OFL licensee at all! And I am unsure that this interpretation is correct in the first place. But let's assume you're right about the OFL.
Even then, I would contend this:
The copyright holder of a font, of course, can choose how to license it. So, if I were the sole copyright holder on a font, for instance, I could choose to make it available under the OFL, but also provide it under the Apache license. There's no provision in using the OFL which restricts the copyright holders themselves. If I wanted to, I could release a font under the OFL, but I could also sell it bare (the one thing the OFL doesn't do!) or relicense it — it all works, since it's my copyright.
So, accordingly, URW has the ability to license their fonts as they see fit. And they themselves write that "The URW++ Core 35 fonts, Version 2.0 are distributed under the GNU Affero General Public License, Version 3 with an exemption, The LaTeX Project Public License, Version 1.3c and the SIL Open Font License, Version 1.1. If you use the fonts, you may choose which license is most suitable for you. If you extend or modify the fonts, you may release your modified versions under any combination of the three licenses." Even if your interpretation of the OFL itself holds, this explicitly granted permission to license under any combination of these terms allows me to do so. This permission goes beyond the permissions of the OFL, and cannot be revoked once given, of course. The language could be construed as creating a "URW License" (no name given), which gives the right to copy and then release under any combination of three licenses.

**Comment by dbenjaminmiller** [comment]
Or, for users downstream of me who take an excessively narrow view of the OFL, they can just use it.
